---
chdir: '/opt/app/lige'
environment: production
address: 0.0.0.0
port: 5555
timeout: 30
log: /opt/app/lige/log/thin.log
pid: /opt/app/lige/tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []
wait: 30
servers: 1
daemonize: true
